export const AUTH_USER_SET = 'AUTH_USER_SET';
export const AUTH_USER_RESET = 'AUTH_USER_RESET';

export const UPDATE_PLAN = 'UPDATE_PLAN';

export const ADD_CLAUSE = 'ADD_CLAUSE';
export const REMOVE_CLAUSES = 'REMOVE_CLAUSES';
export const UPDATE_CLAUSE = 'UPDATE_CLAUSE';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const REMOVE_DOCUMENT = 'REMOVE_DOCUMENT';
export const MOVE_CLAUSE_UP = 'MOVE_CLAUSE_UP';
export const MOVE_CLAUSE_DOWN = 'MOVE_CLAUSE_DOWN';
export const MOVE_CLAUSE_TO = 'MOVE_CLAUSE_TO';

export const UPDATE_AVENUE = 'UPDATE_AVENUE';
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const REMOVE_PARTICIPANT = 'REMOVE_PARTICIPANT';

export const ADD_ACCORD = 'ADD_ACCORD';

export const UPDATE_NAME = 'UPDATE_NAME';

export const REQUEST_PLAN_STARTED = 'REQUEST_PLAN_STARTED';
export const REQUEST_PLAN_FAILED = 'REQUEST_PLAN_FAILED';
export const REQUEST_PLAN_SUCCESS = 'REQUEST_PLAN_SUCCESS';

export const REQUEST_BRACKET_STARTED = 'REQUEST_BRACKET_STARTED';
export const REQUEST_BRACKET_FAILED = 'REQUEST_BRACKET_FAILED';
export const REQUEST_BRACKET_SUCCESS = 'REQUEST_BRACKET_SUCCESS';

export const UPDATE_FOCUS = 'UPDATE_FOCUS';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const UPDATE_GUARANTEE = 'UPDATE_GUARANTEE';

export const BLUR = 'BLUR';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
